"""Analyze a one-dimensional impedance step-response CSV.

Compatible with impedance_response.csv generated by impedance_1d.py.
Only the Python standard library is required.
"""

import argparse
import csv
import json
import math
from pathlib import Path


def mean(values: list[float]) -> float:
    if not values:
        raise ValueError("metric window contains no samples")
    return sum(values) / len(values)


def rms(values: list[float]) -> float:
    if not values:
        raise ValueError("metric window contains no samples")
    return math.sqrt(sum(value * value for value in values) / len(values))


def load_rows(path: Path) -> list[dict[str, float]]:
    required = {"time_s", "force_n", "position_m"}
    with path.open(newline="", encoding="utf-8") as source:
        reader = csv.DictReader(source)
        missing = required.difference(reader.fieldnames or [])
        if missing:
            raise ValueError(f"missing CSV columns: {sorted(missing)}")
        rows = [{name: float(row[name]) for name in required} for row in reader]
    if len(rows) < 3:
        raise ValueError("at least three samples are required")
    if any(b["time_s"] <= a["time_s"] for a, b in zip(rows, rows[1:])):
        raise ValueError("time_s must be strictly increasing")
    return rows


def analyze(
    rows: list[dict[str, float]], step_on_s: float, step_off_s: float
) -> dict[str, float]:
    if not rows[0]["time_s"] < step_on_s < step_off_s < rows[-1]["time_s"]:
        raise ValueError("step times must lie strictly inside the log interval")

    step_duration = step_off_s - step_on_s
    baseline = [row for row in rows if row["time_s"] < step_on_s]
    steady = [
        row
        for row in rows
        if step_off_s - 0.2 * step_duration <= row["time_s"] < step_off_s
    ]
    released = [row for row in rows if row["time_s"] >= step_off_s]

    baseline_position = mean([row["position_m"] for row in baseline])
    steady_position = mean([row["position_m"] for row in steady])
    steady_force = mean([row["force_n"] for row in steady])
    displacement = steady_position - baseline_position
    if abs(displacement) < 1e-12:
        raise ValueError("steady displacement is too small to estimate stiffness")

    direction = 1.0 if displacement >= 0.0 else -1.0
    peak_magnitude = max(
        direction * (row["position_m"] - baseline_position)
        for row in rows
        if step_on_s <= row["time_s"] < step_off_s
    )
    steady_magnitude = abs(displacement)

    return {
        "baseline_position_m": baseline_position,
        "steady_displacement_m": displacement,
        "steady_force_n": steady_force,
        "estimated_stiffness_n_m": steady_force / displacement,
        "peak_displacement_m": direction * peak_magnitude,
        "overshoot_percent": max(
            0.0, (peak_magnitude - steady_magnitude) / steady_magnitude * 100.0
        ),
        "released_position_rms_m": rms(
            [row["position_m"] - baseline_position for row in released]
        ),
        "sample_period_mean_s": (
            rows[-1]["time_s"] - rows[0]["time_s"]
        ) / (len(rows) - 1),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("csv_path", type=Path)
    parser.add_argument("--step-on", type=float, default=0.5)
    parser.add_argument("--step-off", type=float, default=1.5)
    args = parser.parse_args()

    metrics = analyze(load_rows(args.csv_path), args.step_on, args.step_off)
    print(json.dumps(metrics, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
